namadepan = input("Masukan Nama Depan =")
namabelakang = input ("Masukan Nama Belakang =")
fullnama=input("namadepan+namabelakang")
nim= input("masukan nim=")
univ=input("universitas muhammadiyah surakarta")
fakultas= input("fakultas")
print("pendidikan teknik informatika".center(50))
print ("Nama =[{}]") , format (namadepan)
print ("Nama =[{}]") , format (namabelakang)
print ("Nama =[{}]") , format (fullnama)
print ("nim =[{}]") , format (nim)
print ("fakultas =[{}]") , format (fakultas)
print (univ.upper().center(50))